// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/services/wasmdealer/v1/wasmdealer.proto

package wasmdealer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WasmdealerClient is the client API for Wasmdealer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WasmdealerClient interface {
	// Create a task.
	Create(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
}

type wasmdealerClient struct {
	cc grpc.ClientConnInterface
}

func NewWasmdealerClient(cc grpc.ClientConnInterface) WasmdealerClient {
	return &wasmdealerClient{cc}
}

func (c *wasmdealerClient) Create(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.wasmdealer.v1.Wasmdealer/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WasmdealerServer is the server API for Wasmdealer service.
// All implementations should embed UnimplementedWasmdealerServer
// for forward compatibility
type WasmdealerServer interface {
	// Create a task.
	Create(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
}

// UnimplementedWasmdealerServer should be embedded to have forward compatible implementations.
type UnimplementedWasmdealerServer struct {
}

func (UnimplementedWasmdealerServer) Create(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

// UnsafeWasmdealerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WasmdealerServer will
// result in compilation errors.
type UnsafeWasmdealerServer interface {
	mustEmbedUnimplementedWasmdealerServer()
}

func RegisterWasmdealerServer(s grpc.ServiceRegistrar, srv WasmdealerServer) {
	s.RegisterService(&Wasmdealer_ServiceDesc, srv)
}

func _Wasmdealer_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasmdealerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.wasmdealer.v1.Wasmdealer/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasmdealerServer).Create(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wasmdealer_ServiceDesc is the grpc.ServiceDesc for Wasmdealer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wasmdealer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containerd.services.wasmdealer.v1.Wasmdealer",
	HandlerType: (*WasmdealerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Wasmdealer_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/wasmdealer/v1/wasmdealer.proto",
}
